service: nestjs-lambda

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2

functions:
  main:
    handler: src/lambda.handler
    events:
      - http:
          method: any
          path: /{any+}