service: nestjs-lambda

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2

custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules: true
    packagerOptions:
      scripts:
        - npm_config_platform=linux npm_config_arch=x64 npm install bcrypt

functions:
  main:
    handler: src/lambda.handler
    events:
      - http:
          method: any
          path: /{any+}